apps/courses/urls.py
#!/user/bin/env/python
# -*- coding:utf-8 -*-


from django.conf.urls import url, include

from .views import CourseListView
from .views import CourseDetailView
from .views import CourseInfoView
from .views import CourseCommentView
from .views import AddCommentsView
from .views import VideoPlayView



urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name='course_list'),
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='course_detail'),
    url(r'^info/(?P<course_id>\d+)/$', CourseInfoView.as_view(), name='course_info'),
    url(r'comment/(?P<course_id>\d+)/$', CourseCommentView.as_view(), name='course_comment'),
    url(r'add_comment/$', AddCommentsView.as_view(), name='add_comment'), #添加课程评论
    url(r'video_play/(?P<video_id>\d+)/$', VideoPlayView.as_view(), name='video_play')
]

apps/organization/urls.py
#!/user/bin/env/python
# -*- coding:utf-8 -*-
__author__ = 'drw'
__date__ = '2017/2/3 11:29'

from django.conf.urls import url, include

from .views import OrgListView #引入课程机构首页类
from .views import AddUserAskView
from .views import OrgHomeView
from .views import OrgCourseView
from .views import OrgDescView
from .views import OrgTeacherView
from .views import AddFavView
from .views import TeacherListView
from .views import TeacherDetailView


urlpatterns = [
    url(r'^list/$', OrgListView.as_view(), name='org_list'),    #课程机构首页
    url(r'^add_ask/$', AddUserAskView.as_view(), name='add_ask'), #课程咨询提交
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name='org_home'),
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name='org_course'),
    url(r'^detail/(?P<org_id>\d+)/$', OrgDescView.as_view(), name='org_detail'),
    url(r'^org_teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name='org_teacher'),
    url(r'^add_fav/$', AddFavView.as_view(), name='add_fav'),#机构收藏
    url(r'^teacher/list/$', TeacherListView.as_view(), name='teacher_list'), #讲师列表页
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name='teacher_detail')
]

edu/urls.py
# _*_ encoding:utf-8 _*_
"""edu URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from users import views
import xadmin
from django.views.static import serve #处理静态文件
from edu.settings import MEDIA_ROOT


from users.views import LoginView #引入登陆类
from users.views import RegisterView #引入注册类
from users.views import ActiveUserView #引入激活类
from users.views import ForgetPwdView #引入找回密码类
from users.views import ResetUserView
from users.views import ModifyPwdView
from users.views import LogOutView
from users.views import IndexView




urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogOutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^captcha/', include('captcha.urls')),#验证码
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name='user_active'),
    url(r'^forgetpwd/$', ForgetPwdView.as_view(), name='forget_pwd'),
    url(r'^reset/(?P<active_code>.*)/$', ResetUserView.as_view(), name='reset_pwd'),
    url(r'^modifypwd/$', ModifyPwdView.as_view(), name='modify_pwd'),
    url(r'^org/', include('organization.urls', namespace='org')),#课程机构url配置
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT}), #显示后台图片
    # url(r'^static/(?P<path>.*)$', serve, {"document_root":STATIC_ROOT}), #生产环境下显示静态文件
    url(r'^course/', include('courses.urls', namespace='course')),#课程相关url配置
    url(r'^user/', include('users.urls', namespace='user')),#课程相关url配置
    url(r'^ueditor/',include('DjangoUeditor.urls' )),#富文本相关url
]


#全局404页面配置
handler404 = 'users.views.page_not_found'
#全局500配置
handler500 = 'users.views.page_error'

apps/courses/models.py
# _*_ encoding:utf-8 _*_
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
from organization.models import CourseOrg, Teacher
from DjangoUeditor.models import UEditorField

# Create your models here.


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name=u'课程机构', null=True, blank=True)
    name = models.CharField(verbose_name=u'课程名', max_length=50)
    desc = models.TextField(verbose_name=u'课程描述')
    teacher = models.ForeignKey(Teacher, verbose_name=u'讲师', null=True, blank=True)
    detail =  UEditorField(verbose_name=u'课程详情',width=600, height=300, imagePath="courses/ueditor/", filePath="courses/ueditor/",default='')
    is_banner = models.BooleanField(default=False, verbose_name=u'是否轮播')
    degree = models.CharField(verbose_name=u'难度', choices=(('cj', u'初级'), ('zj', u'中级'), ('gj', u'高级')), max_length=2)
    learn_times = models.IntegerField(verbose_name=u'学习时长(分钟数)',default=0)
    students = models.IntegerField(verbose_name=u'学习人数', default=0)
    fav_nums = models.IntegerField(verbose_name=u'收藏人数', default=0)
    imgage = models.ImageField(verbose_name=u'封面图', upload_to='courses/%Y/%m', max_length=100)
    click_nums = models.IntegerField(verbose_name=u'课程点击数', default=0)
    category = models.CharField(max_length=20, verbose_name=u'课程类别', null=True, blank=True)
    tag = models.CharField(verbose_name=u'课程标签', default='', max_length=10)
    add_time = models.DateTimeField(verbose_name=u'添加时间', default=datetime.now)
    youneed_know = models.CharField(verbose_name=u'课程需知', max_length=300, default='')
    teacher_tell = models.CharField(verbose_name=u'老师告诉你', max_length=300, default='')

    class Meta:
        verbose_name = u'课程'
        verbose_name_plural = verbose_name

    def get_zj_nums(self):
        '''获取章节数'''
        return self.lesson_set.all().count()
    get_zj_nums.short_description = '章节数'

    def go_to(self):
        from django.utils.safestring import mark_safe
        return mark_safe("<a href='https://www.baidu.com'>跳钻</a>")
    go_to.short_description = '跳转'

    def get_learn_users(self):
        '''获得学习用户'''
        return self.usercourse_set.all()[:5]

    def get_course_lesson(self):
        '''获取课程所有章节'''
        return self.lesson_set.all()

    def __unicode__(self):
        return self.name


class BannerCourse(Course):
    '''同一张表,但是可以分开管理不同数据,数据分类管理'''
    class Meta:
        verbose_name = u'轮播课程'
        verbose_name_plural = verbose_name
        proxy = True


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'课程')
    name = models.CharField(verbose_name=u'章节名', max_length=100)
    add_time = models.DateTimeField(verbose_name=u'添加时间', default=datetime.now)

    class Meta:
        verbose_name = u'章节'
        verbose_name_plural = verbose_name

    def get_all_video(self):
        '''获得所有视频'''
        return self.video_set.all()

    def __unicode__(self):
        return self.name

class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name=u'章节')
    name = models.CharField(verbose_name=u'视频名', max_length=100)
    url = models.CharField(max_length=200, verbose_name=u'访问地址', default='')
    learn_times = models.IntegerField(verbose_name=u'学习时长(分钟数)', default=0)
    add_time = models.DateTimeField(verbose_name=u'添加时间', default=datetime.now)

    class Meta:
        verbose_name = u'视频'
        verbose_name_plural = verbose_name
    def __unicode__(self):
        return self.name

class CourseResouce(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'课程')
    name = models.CharField(verbose_name=u'名称', max_length=100)
    download = models.FileField(verbose_name=u'资源文件', upload_to='course/resource/%Y/%m', max_length=100)
    add_time = models.DateTimeField(verbose_name=u'添加时间', default=datetime.now)

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name
    def __unicode__(self):
        return self.name

templates/course/course-comment.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static  'css/muke/course/course-comment.css' %}" />



{% endblock %}
{% block title %}用户评论{% endblock %}
{% block bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
				<li><a href="{% url 'course:course_detail' course.id %}">课程详情</a>></li>
                <li>用户评论</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
    <div id="main">
        <div class="course-infos">
            <div class="w pr">
                <div style="height: 15px" class="path"></div>
                <div class="hd">
                    <h2 class="l">{{ course.name }}</h2>
                </div>
                <div class="statics clearfix">
                    <div class="static-item ">
                        <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                        <span class="meta">难度</span>
                        <em></em>
                    </div>
                    <div class="static-item static-time">
                        <span class="meta-value">{{ course.learn_times }}分钟</span>
                        <span class="meta">时长</span>
                        <em></em>
                    </div>
                    <div class="static-item">
                        <span class="meta-value"><strong>{{ course.students }}</strong></span>
                        <span class="meta">学习人数</span>
                        <em></em>
                    </div>
                </div>
            </div>
        </div>
        <div class="course-info-main clearfix w has-progress">
            <div class="info-bar clearfix">
                <div class="content-wrap clearfix">
                    <div class="content">
                        <div class="mod-tab-menu">
                            <ul class="course-menu clearfix">
                                <li><a class="ui-tabs-active " id="learnOn"  href="{% url 'course:course_info' course.id %}"><span>章节</span></a></li>
                                <li><a id="commentOn" class="active" href="{% url 'course:course_comment' course.id %}"><span>评论</span></a></li>
                            </ul>
                        </div>
                        <!--发布评论-->
                        <div id="js-pub-container" class="issques clearfix js-form">
                            <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                                <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！" ></textarea>
                            </div>
                            <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                            <p class="global-errortip js-global-error"></p>
                        </div>
                        <div id="course_note">
                            <ul class="mod-post" id="comment-list">
                                {% for comment in all_comments %}
                                    <li class="post-row">
                                        <div class="media">
                                            <span target="_blank"><img src='{{ MEDIA_URL }}{{ comment.user.img }}' width='40' height='40' /></span>
                                        </div>
                                        <div class="bd">
                                            <div class="tit">
                                                <span target="_blank">{{ comment.user.nickname }}</span>
                                            </div>
                                            <p class="cnt">{{ comment.comments }}</p>
                                            <div class="footer clearfix">
                                                <span title="创建时间" class="l timeago">时间：{{ comment.add_time }}</span>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                   <div class="aside r">
                        <div class="bd">
                            <div class="box mb40">
                                <h4>资料下载</h4>
                                <ul class="downlist">
                                    {% for course_resource in all_resource %}
                                        <li>
                                            <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ course_resource.name }}</span>
                                            <a href="{{ MEDIA_URL }}{{ course_resource.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="box mb40">
                                <h4>讲师提示</h4>
                                <div class="teacher-info">
                                    <a href="" target="_blank">
                                        <img src="{{ MEDIA_URL }}{{ course.teacher.image }}" width='80' height='80' />
                                    </a>
                                    <span class="tit">
                                        <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
                                    </span>
                                    <span class="job">{{ course.teacher.work_position }}</span>
                                </div>
                                <div class="course-info-tip">
                                    <dl class="first">
                                        <dt>课程须知</dt>
                                        <dd class="autowrap">{{ course.youneed_know }}</dd>
                                    </dl>
                                    <dl>
                                        <dt>老师告诉你能学到什么？</dt>
                                        <dd class="autowrap">{{ course.teacher_tell }}</dd>
                                    </dl>
                                </div>
                            </div>
                            <div class="cp-other-learned  js-comp-tabs">
                                <div class="cp-header clearfix">
                                    <h2 class="cp-tit l">该课的同学还学过</h2>
                                </div>
                                <div class="cp-body">
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                        <!-- img 200 x 112 -->
                                        <ul class="other-list">
                                            {% for relate_course in relate_courses %}
                                                <li class="curr">
                                                    <a href="{% url 'course:course_detail' relate_course.id %}" target="_blank">
                                                        <img src="{{ MEDIA_URL }}{{ relate_course.imgage }}" alt="{{ relate_course.name }}">
                                                        <span class="name autowrap">{{ relate_course.name }}</span>
                                                    </a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
        //添加评论
        $('#js-pl-submit').on('click', function(){
            var comments = $("#js-pl-textarea").val()
            if(comments == ""){
                alert("评论不能为空")
                return
            }
            $.ajax({
                cache: false,
                type: "POST",
                url:"{% url 'course:add_comment' %}",
                data:{'course_id':{{ course.id }}, 'comments':comments},
                async: true,
                beforeSend:function(xhr, settings){
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function(data) {
                    if(data.status == 'fail'){
                        if(data.msg == '用户未登录'){
                            window.location.href="/login/";
                        }else{
                            alert(data.msg)
                        }

                    }else if(data.status == 'success'){
                        window.location.reload();//刷新当前页面.
                    }
                }
            });
        });
    </script>
{% endblock %}

templates/course/course-list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}公开课列表{% endblock %}
{% block bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li>公开课</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
    <section>
	    <div class="wp">
		    <div class="list" style="margin-top:0;">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="{% ifequal sort '' %}active{% endifequal %}"><a href="?sort=">最新 </a></li>
						<li class="{% ifequal sort 'hot' %}active{% endifequal %}"><a href="?sort=hot">最热门</a></li>
						<li class="{% ifequal sort 'students' %}active{% endifequal %}"><a href="?sort=students">参与人数</a></li>
					</ul>
				</div>
                <div id="inWindow">
                    <div class="tab_cont " id="content">
					<div class="group_list">
                        {% for course in all_course.object_list %}
                            <div class="box">
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <img width="280" height="350" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.imgage }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' course.id %}">
                                        <h2>{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}&nbsp;&nbsp;</span>
                                </div>
                                <div class="bottom">
                                    <a href="{% url 'course:course_detail' course.id %}"><span class="fl">来自{{ course.course_org.name }}</span></a>
                                    <span class="star fr  notlogin
                                        " data-favid="15">
                                        {{ course.fav_nums }}
                                    </span>
                                </div>
                            </div>
                        {% endfor %}
					</div>
                    <div class="pageturn">
                        <ul class="pagelist">
                            {% if all_course.has_previous %}
                                <li class="long"><a href="?{{ all_course.previous_page_number.querystring }}">上一页</a></li>
                            {% endif %}
                            {% for page in all_course.pages %}
                                {% if page %}
                                    {% ifequal page all_course.number %}
                                        <li class="active"><a href="?page=1">{{ page }}</a></li>
                                    {% else %}
                                        <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                    {% endifequal %}
                                {% else %}
                                   <li class="none"><a href="">...</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if all_course.has_next %}
                                <li class="long"><a href="?{{ all_course.next_page_number.querystring }}">下一页</a></li>
                            {% endif %}
                        </ul>
                    </div>
				</div>
                </div>
			</div>
			<div class="right layout">
				<div class="head">热门课程推荐</div>
				<div class="group_recommend">
                    {% for item in hot_course %}
                        <dl>
                            <dt>
                                <a target="_blank" href="{% url 'course:course_detail' item.id %}">
                                    <img width="240" height="220" class="scrollLoading" src="{{ MEDIA_URL }}{{ item.imgage }}"/>
                                </a>
                            </dt>
                            <dd>
                                <a target="_blank" href="{% url 'course:course_detail' item.id %}"><h2> {{ item.name }}</h2></a>
                                <span class="fl">难度：<i class="key">{{ item.get_degree_display }}</i></span>
                            </dd>
                        </dl>
                    {% endfor %}
				</div>
			</div>
		</div>
	    </div>
    </section>
{% endblock %}

templates/course/course-video.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
{% endblock %}
{% block title %}{{ course.name }}{% endblock %}
{% block bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
				<li><a href="{% url 'course:course_detail' course.id %}">课程详情</a>></li>
                <li>章节信息</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
    <div id="main">
        <div class="course-infos">
            <div class="w pr">
                <div style="height: 15px" class="path"></div>
                <div class="hd">
                    <h2 class="l">{{ course.name }}</h2>
                </div>
                <div class="statics clearfix">
                    <div class="static-item ">
                        <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                        <span class="meta">难度</span>
                        <em></em>
                    </div>
                    <div class="static-item static-time">
                        <span class="meta-value">{{ course.learn_times }}分钟</span>
                        <span class="meta">时长</span>
                        <em></em>
                    </div>
                    <div class="static-item">
                        <span class="meta-value"><strong>{{ course.students }}</strong></span>
                        <span class="meta">学习人数</span>
                        <em></em>
                    </div>
                </div>
            </div>
        </div>
        <div class="course-info-main clearfix w has-progress">
            <div class="info-bar clearfix">
                <div class="content-wrap clearfix">
                    <div class="content">
                        <div class="mod-tab-menu">
                            <ul class="course-menu clearfix">
                                <li><a class="ui-tabs-active active" id="learnOn"  href="{% url 'course:course_info' course.id %}"><span>章节</span></a></li>
                                <li><a id="commentOn" class="" href="{% url 'course:course_comment' course.id %}"><span>评论</span></a></li>
                            </ul>
                        </div>
{#                        <div id="notice" class="clearfix">#}
{#                            <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">Spring的文档以及相关的jar文件已上传</a> </div>#}
{#                        </div>#}
                        <div class="mod-chapters">
                            {% for lesson in course.get_course_lesson %}
                                <div class="chapter chapter-active" >
                                    <h3>
                                        <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                                    </h3>
                                    <ul class="video">
                                        {% for video in lesson.get_all_video %}
                                            <li>
                                                <a target="_blank" href='{% url "course:video_play" video.id %}' class="J-media-item studyvideo">{{ video.name }}({{ video.learn_times }})
                                                    <i class="study-state"></i>
                                                </a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="aside r">
                        <div class="bd">
                            <div class="box mb40">
                                <h4>资料下载</h4>
                                <ul class="downlist">
                                    {% for course_resource in all_resource %}
                                        <li>
                                            <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ course_resource.name }}</span>
                                            <a href="{{ MEDIA_URL }}{{ course_resource.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="box mb40">
                                <h4>讲师提示</h4>
                                <div class="teacher-info">
                                    <a href="" target="_blank">
                                        <img src="{{ MEDIA_URL }}{{ course.teacher.image }}" width='80' height='80' />
                                    </a>
                                    <span class="tit">
                                        <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
                                    </span>
                                    <span class="job">{{ course.teacher.work_position }}</span>
                                </div>
                                <div class="course-info-tip">
                                    <dl class="first">
                                        <dt>课程须知</dt>
                                        <dd class="autowrap">{{ course.youneed_know }}</dd>
                                    </dl>
                                    <dl>
                                        <dt>老师告诉你能学到什么？</dt>
                                        <dd class="autowrap">{{ course.teacher_tell }}</dd>
                                    </dl>
                                </div>
                            </div>
                            <div class="cp-other-learned  js-comp-tabs">
                                <div class="cp-header clearfix">
                                    <h2 class="cp-tit l">该课的同学还学过</h2>
                                </div>
                                <div class="cp-body">
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                        <!-- img 200 x 112 -->
                                        <ul class="other-list">
                                            {% for relate_course in relate_courses %}
                                                <li class="curr">
                                                    <a href="{% url 'course:course_detail' relate_course.id %}" target="_blank">
                                                        <img src="{{ MEDIA_URL }}{{ relate_course.imgage }}" alt="{{ relate_course.name }}">
                                                        <span class="name autowrap">{{ relate_course.name }}</span>
                                                    </a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
{% endblock %}