apps/courses/urls.py
#!/user/bin/env/python
# -*- coding:utf-8 -*-


from django.conf.urls import url, include

from .views import CourseListView
from .views import CourseDetailView
from .views import CourseInfoView
from .views import CourseCommentView
from .views import AddCommentsView
from .views import VideoPlayView



urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name='course_list'),
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='course_detail'),
    url(r'^info/(?P<course_id>\d+)/$', CourseInfoView.as_view(), name='course_info'),
    url(r'comment/(?P<course_id>\d+)/$', CourseCommentView.as_view(), name='course_comment'),
    url(r'add_comment/$', AddCommentsView.as_view(), name='add_comment'), #添加课程评论
    url(r'video_play/(?P<video_id>\d+)/$', VideoPlayView.as_view(), name='video_play')
]

apps/organization/urls.py
#!/user/bin/env/python
# -*- coding:utf-8 -*-
__author__ = 'drw'
__date__ = '2017/2/3 11:29'

from django.conf.urls import url, include

from .views import OrgListView #引入课程机构首页类
from .views import AddUserAskView
from .views import OrgHomeView
from .views import OrgCourseView
from .views import OrgDescView
from .views import OrgTeacherView
from .views import AddFavView
from .views import TeacherListView
from .views import TeacherDetailView


urlpatterns = [
    url(r'^list/$', OrgListView.as_view(), name='org_list'),    #课程机构首页
    url(r'^add_ask/$', AddUserAskView.as_view(), name='add_ask'), #课程咨询提交
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name='org_home'),
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name='org_course'),
    url(r'^detail/(?P<org_id>\d+)/$', OrgDescView.as_view(), name='org_detail'),
    url(r'^org_teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name='org_teacher'),
    url(r'^add_fav/$', AddFavView.as_view(), name='add_fav'),#机构收藏
    url(r'^teacher/list/$', TeacherListView.as_view(), name='teacher_list'), #讲师列表页
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name='teacher_detail')
]

apps/users/urls.py
#!/user/bin/env/python
# -*- coding:utf-8 -*-


from django.conf.urls import url, include

from .views import UserInfoView, UploadImageView, UpdatePwdView, SendEmailCodeView, UpdateEmailView, UserCourseView
from .views import MyfavOrgView, MyfavTeacherView, MyfavCourseView, UserMessageView


urlpatterns = [
    url(r'^info/$', UserInfoView.as_view(), name='user_info'),#用户信息
    url(r'^image/upload/$',UploadImageView.as_view(), name='image_upload'),#用户头像上传
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name='update_pwd'), #用户个人中心修改密码
    url(r'^sendemail_code/$', SendEmailCodeView.as_view(), name='sendemail_code'), #发送邮箱验证码
    url(r'^update_email/$', UpdateEmailView.as_view(), name='update_email'), #修改邮箱
    url(r'^course/$', UserCourseView.as_view(), name='user_course'),#用户课程
    url(r'^myfav/org/$', MyfavOrgView.as_view(), name='myfav_org'),#收藏课程机构
    url(r'^myfav/teacher/$', MyfavTeacherView.as_view(), name='myfav_teacher'),  # 收藏授课教师
    url(r'^myfav/course/$', MyfavCourseView.as_view(), name='myfav_course'),  # 收藏课程
    url(r'^message/$', UserMessageView.as_view(), name='user_message'),#用户消息
]

edu/urls.py
# _*_ encoding:utf-8 _*_
"""edu URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from users import views
import xadmin
from django.views.static import serve #处理静态文件
from edu.settings import MEDIA_ROOT


from users.views import LoginView #引入登陆类
from users.views import RegisterView #引入注册类
from users.views import ActiveUserView #引入激活类
from users.views import ForgetPwdView #引入找回密码类
from users.views import ResetUserView
from users.views import ModifyPwdView
from users.views import LogOutView
from users.views import IndexView




urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogOutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^captcha/', include('captcha.urls')),#验证码
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name='user_active'),
    url(r'^forgetpwd/$', ForgetPwdView.as_view(), name='forget_pwd'),
    url(r'^reset/(?P<active_code>.*)/$', ResetUserView.as_view(), name='reset_pwd'),
    url(r'^modifypwd/$', ModifyPwdView.as_view(), name='modify_pwd'),
    url(r'^org/', include('organization.urls', namespace='org')),#课程机构url配置
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT}), #显示后台图片
    # url(r'^static/(?P<path>.*)$', serve, {"document_root":STATIC_ROOT}), #生产环境下显示静态文件
    url(r'^course/', include('courses.urls', namespace='course')),#课程相关url配置
    url(r'^user/', include('users.urls', namespace='user')),#课程相关url配置
    url(r'^ueditor/',include('DjangoUeditor.urls' )),#富文本相关url
]


#全局404页面配置
handler404 = 'users.views.page_not_found'
#全局500配置
handler500 = 'users.views.page_error'

apps/users/forms.py
#!/user/bin/env/python
# -*- coding:utf-8 -*-
__author__ = 'drw'
__date__ = '2017/2/1 10:03'

from django import forms
from captcha.fields import CaptchaField
from .models import UserProfile

class LoginForm(forms.Form):
    '''登陆表单验证'''
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=6)

class RegisterForm(forms.Form):
    '''注册表单验证'''
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=6)
    captcha = CaptchaField(error_messages={"invalid":u"验证码错误"})

class ForgetForm(forms.Form):
    '''找回密码表单'''
    email = forms.EmailField(required=True)
    captcha = CaptchaField(error_messages={"invalid":u"验证码错误"})

class ModifyForm(forms.Form):
    '''修改密码表单验证'''
    password1 = forms.CharField(required=True, min_length=6)
    password2 = forms.CharField(required=True, min_length=6)

class UploadImageForm(forms.ModelForm):
    '''修改头像'''
    class Meta:
        model = UserProfile
        fields = ['img']

class UserInfoForm(forms.ModelForm):
    '''修改个人信息'''
    class Meta:
        model = UserProfile
        fields = ['nickname', 'gender', 'birday', 'address', 'mobile']

apps/users/views.py
# _*_ encoding:utf-8 _*_
import json
from django.shortcuts import render, HttpResponse
from django.contrib.auth import authenticate, login, logout #django提供的验证方法
from django.contrib.auth.backends import ModelBackend
from django.db.models import Q
from django.views.generic.base import View
from django.http import HttpResponse, HttpResponseRedirect
from utils.mixin_utils import LoginRequiredMixin
from pure_pagination import Paginator,EmptyPage, PageNotAnInteger

from datetime import datetime
import time

from .models import UserProfile,EmailVerifyRecord, Banner
from forms import LoginForm, RegisterForm, ForgetForm, ModifyForm
from django.contrib.auth.hashers import make_password #密码加密
from utils.email_send import send_regiser_email #引入邮箱功能
from .forms import UploadImageForm, UserInfoForm
from operation.models import UserCourse, UserFavorite, UserMessage
from organization.models import CourseOrg, Teacher
from courses.models import Course


# Create your views here.


class CustomBackend(ModelBackend):
    '''
    使登陆能验证邮箱或用户名
    '''
    def authenticate(self, username=None, password=None, **kwargs):
        try:
            user = UserProfile.objects.get(Q(username=username)|Q(email=username)) #Q来做"或"
            if user.check_password(password):
                return user
        except Exception as e:
            return None


class LoginView(View):
    def get(self, request):
        return render(request, 'login.html', {})
    def post(self, request):
        '''登陆'''
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = request.POST.get('username', None)
            pwd = request.POST.get('password', None)
            user = authenticate(username=username, password=pwd)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    from django.core.urlresolvers import reverse
                    return HttpResponseRedirect(reverse("index"))
                else:
                    return render(request, "login.html", {"msg": "用户未激活"})
            else:
                return render(request, "login.html", {"msg":"用户名或密码错误"})
        else:
            return render(request, "login.html", {"login_form":login_form})


class RegisterView(View):
    def get(self, request):
        register_form = RegisterForm() #实例化
        return render(request, "register.html", {'register_form':register_form})
    def post(self, request):
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            username = request.POST.get('email', '')
            if UserProfile.objects.filter(email=username):
                return render(request, "register.html", {"register_form": register_form, "msg":"用户已经存在"})
            pwd = request.POST.get('password',  '')
            user_profile = UserProfile()
            user_profile.username = username
            user_profile.email = username
            user_profile.is_active = False
            user_profile.password = make_password(pwd)
            user_profile.save()

            #写入欢迎注册消息
            user_message = UserMessage()
            user_message.user = user_profile.id
            user_message.message = '欢迎注册'
            user_message.save()

            send_regiser_email(username, "register")
            return render(request, "login.html")
        else:
            return render(request, "register.html", {"register_form":register_form})


class LogOutView(View):
    def get(self, request):
        logout(request)
        #django重定向
        from django.core.urlresolvers import reverse
        return HttpResponseRedirect(reverse('index'))

class ActiveUserView(View):
    '''点击邮件,通过验证'''
    def get(self, request, active_code):
        all_records = EmailVerifyRecord.objects.filter(code=active_code)
        if all_records:
            for record in all_records:
                email = record.email
                old_time = str(record.send_time)  #将时间转为字符串
                old_time = old_time.split('.') #以"."分割字符串
                old_time = time.mktime(time.strptime(old_time[0], "%Y-%m-%d %H:%M:%S")) #将第一部分转为时间戳
                now_time = time.time() #现在时间
                if(now_time - old_time >= 15*60):
                    return render(request, "active_fail.html")
                user = UserProfile.objects.get(email=email)
                user.is_active = True
                user.save()
        else:
            return render(request, "active_fail.html")
        return render(request, "login.html")


class ForgetPwdView(View):
    def get(self, request):
        forget_form = ForgetForm()
        return render(request, 'forgetpwd.html', {'forget_form':forget_form})
    def post(self, request):
        forget_form = ForgetForm(request.POST)
        if forget_form.is_valid():
            email = request.POST.get('email', '')
            send_regiser_email(email, 'forget')
            return render(request, 'send_success.html')
        else:
            return render(request, 'forgetpwd.html', {"forget_form":forget_form})


class ResetUserView(View):
    def get(self, request, active_code):
        all_records = EmailVerifyRecord.objects.filter(code=active_code)
        if all_records:
            for record in all_records:
                email = record.email
                old_time = str(record.send_time)  # 将时间转为字符串
                old_time = old_time.split('.')  # 以"."分割字符串
                old_time = time.mktime(time.strptime(old_time[0], "%Y-%m-%d %H:%M:%S"))  # 将第一部分转为时间戳
                now_time = time.time()  # 现在时间
                if (now_time - old_time >= 15 * 60):
                    return render(request, "active_fail.html")
                return render(request, "password_reset.html", {"email":email})
        else:
            return render(request, "active_fail.html")
        return render(request, "login.html")


class ModifyPwdView(View):
    '''修改用户密码'''
    def post(self, request):
        modify_form = ModifyForm(request.POST)
        if modify_form.is_valid():
            pwd1 = request.POST.get('password1', '')
            pwd2 = request.POST.get('password2', '')
            email = request.POST.get('email', '')

            if pwd1 != pwd2:
                return render(request, "password_reset.html", {"email":email, "msg":"密码不一致"})
            user = UserProfile.objects.get(email=email)
            user.password = make_password(pwd1)
            user.save()
            return render(request, "login.html")
        else:
            email = request.POST.get('email', '')
            return render(request, "password_reset.html", {"email": email, "modify_form": modify_form})


class UserInfoView(LoginRequiredMixin, View):
    '''用户个人信息'''
    def get(self, request):
        return render(request, 'user/usercenter-info.html')
    def post(self, request):
        user_info_form = UserInfoForm(request.POST, instance=request.user)
        if user_info_form.is_valid():
            user_info_form.save()
            return HttpResponse('{"status":"success"}', content_type='application/json')
        else:
            return HttpResponse(json.dumps(user_info_form.errors), content_type='application/json')


class UploadImageView(LoginRequiredMixin, View):
    '''修改头像'''
    def post(self, request):
        image_form = UploadImageForm(request.POST, request.FILES, instance=request.user)
        if image_form.is_valid():
           image_form.save()
           return HttpResponse('{"status":"success"}', content_type='application/json')
        else:
            return HttpResponse('{"status":"fail"}', content_type='application/json')


class UpdatePwdView(LoginRequiredMixin, View):
    '''修改个人中心密码'''
    def post(self, request):
        modify_form = ModifyForm(request.POST)
        if modify_form.is_valid():
            pwd1 = request.POST.get('password1', '')
            pwd2 = request.POST.get('password2', '')
            if pwd1 != pwd2:
                return HttpResponse('{"status":"fail","msg":"密码不一致"}', content_type='application/json')
            user = request.user
            user.password = make_password(pwd1)
            user.save()
            return HttpResponse('{"status":"success"}', content_type='application/json')
        else:
            return HttpResponse(json.dumps(modify_form.errors), content_type='application/json')


class SendEmailCodeView(LoginRequiredMixin, View):
    '''发送邮箱验证码'''
    def get(self, request):
        email = request.GET.get('email', '')
        if UserProfile.objects.filter(email=email):
            return HttpResponse('{"email":"邮箱已经存在"}', content_type='application/json')
        send_regiser_email(email, 'update')
        return HttpResponse('{"status":"success"}', content_type='application/json')


class UpdateEmailView(LoginRequiredMixin, View):
    '''修改个人邮箱'''
    def post(self, request):
        email = request.POST.get('email', '')
        code = request.POST.get('code', '')
        existed_records = EmailVerifyRecord.objects.filter(email=email, code=code, send_type='update')
        if existed_records:
            user = request.user
            user.email = email
            user.save()
            return HttpResponse('{"status":"success"}', content_type='application/json')
        else:
            return HttpResponse('{"email":"验证码出错"}', content_type='application/json')


class UserCourseView(LoginRequiredMixin, View):
    '''我的课程'''
    def get(self, request):
        user_courses = UserCourse.objects.filter(user=request.user)
        return render(request, 'user/usercenter-mycourse.html', {
            'user_courses':user_courses
        })


class MyfavOrgView(LoginRequiredMixin, View):
    '''个人中心 收藏机构'''
    def get(self, request):
        org_list = []
        myfav_orgs = UserFavorite.objects.filter(user=request.user, fav_type=2)
        for myfav_org in myfav_orgs:
            org_id = myfav_org.fav_id
            org = CourseOrg.objects.get(id=org_id)

templates/user/usercenter-fav-course.html
{% extends 'user/usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的收藏{% endblock %}
{% block bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="{% url 'user:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'user:myfav_org' %}">课程机构</a> </li>
                        <li ><a href="{% url 'user:myfav_teacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'user:myfav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for item in course_list %}
                            <div class="module1_5 box">
                                <a href="{% url 'course:course_detail' item.id %}">
                                    <img width="214" height="190" src="{{ MEDIA_URL }}{{ item.imgage }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' item.id %}"><h2>{{ item.name }}</h2></a>
                                    <span class="fl">时长：<i class="key">{{ item.learn_times }}</i></span>
                                    <span class="fr">学习人数：{{ item.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl">{{ item.course_org.name }}</span>
                                    <span class="delete-group fr jsDeleteFav_course" data-favid="12"></span>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/user/usercenter-fav-org.html
{% extends 'user/usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的收藏{% endblock %}
{% block bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="{% url 'user:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block right_content %}
     <div class="right" >
         <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
         <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'user:myfav_org' %}">课程机构</a> </li>
                        <li><a href="{% url 'user:myfav_teacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'user:myfav_course' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for item in org_list %}
                        <div class="messages butler_list company company-fav-box">
                            <dl class="des fr">
                                <dt>
                                    <a href="{% url 'org:org_home' item.id %}">
                                        <img width="160" height="90" src="{{ MEDIA_URL }}{{ item.image }}"/>
                                    </a>
                                </dt>
                                <dd>
                                    <h1><a href="{% url 'org:org_home' item.id %}">{{ item.name }}</a></h1>
                                    <div class="pic fl" style="width:auto;">
                                        <img src="{% static 'images/authentication.png' %}"/>
                                        <img src="{% static 'images/gold.png' %}"/>
                                    </div>
                                    <span class="c8 clear">{{ item.city }}</span>
                                    <div class="delete jsDeleteFav_org" data-favid="1"></div>
                                </dd>
                            </dl>
                        </div>
                    {% endfor %}
                </div>
            </div>
     </div>
{% endblock %}

templates/user/usercenter-fav-teacher.html
{% extends 'user/usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的收藏{% endblock %}
{% block bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="{% url 'user:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'user:myfav_org' %}">课程机构</a> </li>
                        <li class="active"><a href="{% url 'user:myfav_teacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'user:myfav_course' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for item in teacher_list %}
                        <div class=" butler_list butler-fav-box">
                            <dl class="des users">
                                <dt>
                                    <a href="{% url 'org:teacher_detail' item.id %}">
                                        <img width="100" height="100" src="{{ MEDIA_URL }}{{ item.image }}"/>
                                    </a>
                                </dt>
                                <dd>
                                    <h1>
                                        <a href="{% url 'org:teacher_detail' item.id %}">
                                            {{ item.name }}<span class="key">认证教师</span>
                                        </a>
                                    </h1>
                                    <ul class="cont clearfix">
                                        <li class="time">工作年限：<span>{{ item.work_years }}年</span></li>
                                        <li class="c7">课程数：<span>{{ item.get_all_course }}</span></li>
                                    </ul>
                                    <ul class="cont clearfix">
                                        <li class="time">工作公司：<span>{{ item.work_company }}</span></li>
                                        <li class="c7">公司职位：<span>{{ item.work_position }}</span></li>
                                    </ul>
                                </dd>
                                <div class="delete jsDeleteFav_teacher" data-favid="1"></div>
                            </dl>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}


            




    

templates/user/usercenter-info.html
{% extends 'user/usercenter-base.html' %}
{% block title %}个人资料{% endblock %}
{% block bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="{% url 'user:user_info' %}">个人中心</a>></li>
                <li>个人资料</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right">
		<div class="personal_des ">
			<div class="head" style="border:1px solid #eaeaea;">
				<h1>个人资料</h1>
			</div>
			<div class="inforcon">
				<div class="left" style="width:242px;">
                    <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>
                    <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off" method="post" action="{% url 'user:image_upload' %}" target='frameFile'>
                        <label class="changearea" for="avatarUp">
                            <span id="avatardiv" class="pic">
                                <img width="100" height="100" class="js-img-show" id="avatarShow" src="{{ MEDIA_URL }}{{ request.user.img }}"/>
                            </span>
                            <span class="fl upload-inp-box" style="margin-left:70px;">
                                <span class="button btn-green btn-w100" id="jsAvatarBtn">修改头像</span>
                                <input type="file" name="img" id="avatarUp" class="js-img-up"/>
                            </span>
                        </label>
                        {% csrf_token %}
                    </form>
                    <div style="border-top:1px solid #eaeaea;margin-top:30px;">
                        <a class="button btn-green btn-w100" id="jsUserResetPwd" style="margin:80px auto;width:100px;">修改密码</a>
                    </div>
				</div>
				<form class="perinform" id="jsEditUserForm" autocomplete="off">
					<ul class="right">
						<li>昵&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;称：
                           <input type="text" name="nickname" id="nick_name" value="{{ request.user.nickname }}" maxlength="10">
                            <i class="error-tips"></i>
                        </li>
						<li>生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日：
                           <input type="text" id="birth_day" name="birday" value="{{ request.user.birday|default_if_none:'' }}" readonly="readonly"/>
                            <i class="error-tips"></i>
						</li>
						<li>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio"  name="gender" value="male" {% if request.user.gender == 'male' %}checked{% endif %}>男</label>
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="gender" value="female" {% if request.user.gender == 'femaile' %}checked{% endif %}>女</label>
						</li>
						<li class="p_infor_city">地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：
                            <input type="text" name="address" id="address" placeholder="请输入你的地址" value="{{ request.user.address }}" maxlength="10">
						    <i class="error-tips"></i>
                        </li>
						<li>手&nbsp;&nbsp;机&nbsp;&nbsp;号：
                            <input type="text" name="mobile" id="mobile" placeholder="请输入你的手机号码" value="{{ request.user.mobile|default_if_none:'' }}" maxlength="11">
                        </li>
                        <li>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱：
                        	<input class="borderno" type="text" name="email" readonly="readonly" value="{{ request.user.email }}"/>
                            <span class="green changeemai_btn">[修改]</span>
                    	</li>
						<li class="button heibtn">
							<input type="button" id="jsEditUserBtn" value="保存">
						</li>
					</ul>
                    {% csrf_token %}
				</form>
			</div>
		</div>
	</div>
{% endblock %}

templates/user/usercenter-mycourse.html
{% extends 'user/usercenter-base.html' %}
{% block title %}我的课程{% endblock %}
{% block bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="{% url 'user:user_info' %}">个人中心</a>></li>
                <li>我的课程</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
     <div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的课程</h1>
			</div>
		</div>
		<div class="personal_des permessage">
			<div class="companycenter">
				<div class="group_list brief">
                    {% for item in user_courses %}
                    <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' item.course.id %}">
                                <img width="214" height="190" class="scrollLoading" src="{{ MEDIA_URL }}{{ item.course.imgage }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' item.course.id %}"><h2>{{ item.course.name }}</h2></a>
                                <span class="fl">课时：<i class="key">{{ item.course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ item.course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ item.course.course_org.name}}</span>
                                <span class="star fr  notlogin" data-favid="15">{{ item.course.fav_nums }}</span>
                            </div>
                        </div>
                    {% endfor %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}